### ISSUE TITLE
selinux labels lost 

### ISSUE THREAD

**Issue by peterwu** [koalagang/doasedit#2]
Since the script moves the temporary file to the original place, the original file's permissions and selinux labels are lost. This could be a serious bug in a SELinux enabled environment. 

The problem I recently ran into is that after /etc/fstab was edited, its SELinux labels were changed to the same as the temporary file, which resulted in failure to mount the file system because systemd-fstab-generator.service needs to read /etc/fstab but got denied access due to wrong SELinux label.

I highly suggest that this logic be redesigned by possibly using the dd command to dd the content of the temporary file to the original file by preserving both permissions and SELinux labels.

Just 2 my cents.

**Comment by koalagang** [comment]
Hi @peterwu. Sounds like a good idea. I hadn't thought of using `dd` before. This should also mean that using `chmod` to modify the regular file permissions would be unnecessary as well. I'm currently on holiday though so I won't be working on this for a couple weeks. I also don't use SELinux so I have no way to test if this fixes the bug in regards to SELinux labels, though it seemed to perfectly preserve regular Linux file permissions and ownership from my brief testing on the commandline. Would you be interested in testing if `dd` preserves SELinux labels and then making a PR to implement this change? Assuming we no longer need `chmod` then I could also reject #1 .

**Comment by koalagang** [comment]
@peterwu 
Okay. I merged your pr (de49cba7b213a682a24e54aceb6983b6116a3281) and redesigned the logic as suggested (dffc94c69dc2243714ea0523e6f5cd61b59963f7).

Apologies for leaving this over a year but better late than never, right?
